// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PollTasksController from "./poll_tasks_controller"
application.register("poll-tasks", PollTasksController)

import ToastsController from "./toasts_controller"
application.register("toasts", ToastsController)

import CapacityController from "./capacity_controller"
application.register("capacity", CapacityController)

import RequestActionController from "./request_action_controller"
application.register("request-action", RequestActionController)
